export const bettlilt = [
  {
    name: 'Классический Чизбургер',
    description: 'Говядина, сыр чеддер, лук, помидор, майонез',
    price: 20,
    count: 1,
    image: require('../assets/klassicheskiy.png'),
  },
  {
    name: 'Бургер с Беконом',
    description: 'Котлета из говядины, хрустящий бекон, сыр, кетчуп',
    price: 25,
    count: 1,
    image: require('../assets/burger_s_bekonom.png'),
  },
  {
    name: 'Чикен бургер',
    description: 'Куриная котлета, лист салата, майонез, помидор',
    price: 25,
    count: 1,
    image: require('../assets/chiken.png'),
  },
  {
    name: 'Спайси Чили Бургер',
    description: 'Говяжий бургер с острым чили, сыр, жареный лук',
    price: 30,
    count: 1,
    image: require('../assets/spaysi.png'),
  },
  {
    name: 'Вегетарианский Бургер',
    description: 'Фалафель, авокадо, томат, веганский майонез',
    price: 45,
    count: 1,
    image: require('../assets/vegeterianskiy.png'),
  },
  {
    name: 'Бургер с Рыбной Котлетой',
    description: 'Рыбная котлета, капустный салат, соус тар-тар',
    price: 45,
    count: 1,
    image: require('../assets/burger_s_ribnoy.png'),
  },
  {
    name: 'Бургер "Барбекю"',
    description: 'Говяжий бургер, барбекю соус, карамелизированный лук, сыр',
    price: 35,
    count: 1,
    image: require('../assets/barbekyu.png'),
  },
  {
    name: 'Грибной Бургер',
    description: 'Говядина, жареные шампиньоны, сливочный соус, сыр',
    price: 30,
    count: 1,
    image: require('../assets/gribnoy.png'),
  },
  {
    name: 'Бургер с Двойной Котлетой',
    description: 'Две говяжьи котлеты, двойной сыр, лук, помидор, соус',
    price: 45,
    count: 1,
    image: require('../assets/dvoynoy.png'),
  },
  {
    name: 'Калифорнийский Бургер',
    description: 'Говядина, листья салата, помидор, сыр, авокадо',
    price: 45,
    count: 1,
    image: require('../assets/kaliforniyskiy.png'),
  },
  {
    name: 'Бургер с Яйцом',
    description: 'Говяжий бургер, жареное яйцо, бекон, сыр',
    price: 20,
    count: 1,
    image: require('../assets/burger_s_yatsom.png'),
  },
  {
    name: 'Гавайский Бургер',
    description: 'Говядина, ананас, сыр, соус терияки',
    price: 19,
    count: 1,
    image: require('../assets/gavayskiy.png'),
  },
  {
    name: 'Текс-Мекс Бургер',
    description: 'Говяжий бургер, сыр, чипсы начос, гуакамоле, сальса',
    price: 35,
    count: 1,
    image: require('../assets/teks_meks.png'),
  },
  {
    name: 'Сырный Бургер',
    description: 'Говядина, три вида сыра, майонез, помидор',
    price: 30,
    count: 1,
    image: require('../assets/sirniy_burger.png'),
  },
  {
    name: 'Блю Чиз Бургер',
    description: 'Говядина, сыр блю чиз, карамелизированный лук, соус',
    price: 20,
    count: 1,
    image: require('../assets/blyu_chiz_burger.png'),
  },
  {
    name: 'Бургер "Дели"',
    description: 'Говядина, копченая ветчина, сыр, горчичный соус',
    price: 35,
    count: 1,
    image: require('../assets/burger_deli.png'),
  },
  {
    name: 'Бургер с Лососем',
    description: 'Гриль лосось, салат, соус цезарь, авокадо',
    price: 45,
    count: 1,
    image: require('../assets/burger_s_lososem.png'),
  },
  {
    name: 'Портерхаус Бургер',
    description: 'Стейк портерхаус, салат, помидор, соус бернез',
    price: 15,
    count: 1,
    image: require('../assets/porterxaus.png'),
  },
  {
    name: 'Корейский Бургер',
    description: 'Говядина, кимчи, сыр, спайси майонез',
    price: 35,
    count: 1,
    image: require('../assets/koreyskiy.png'),
  },
  {
    name: 'Бургер "Бульоньез"',
    description: 'Говядина, соус болоньезе, пармезан, базилик',
    price: 20,
    count: 1,
    image: require('../assets/bulyonez.png'),
  },
];
